apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-configmap-volume
  name: helloworld-configmap-volume
spec:
  containers:
    - image: gcr.io/google-samples/hello-app:1.0
      name: helloworld-configmap-volume
      env:
        - name: TEST_ENV
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: TEST_ENV
      ports:
        - containerPort: 8080
      resources: {}
      volumeMounts:
        - name: my-config-volume
          mountPath: /my-config/TEST_ENV
  volumes:
    - name: my-config-volume
      configMap:
        name: my-config
        items:
          - key: TEST_ENV
            path: keys

  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
