apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-configmap-env
  name: helloworld-configmap-env
spec:
  containers:
    - image: gcr.io/google-samples/hello-app:1.0
      name: helloworld-configmap-env
      env:
        - name: TEST_ENV
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: TEST_ENV
      ports:
        - containerPort: 8080
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
